### PR TITLE
Adapt RouteSimilarity to take aliases into account

### LINKED ISSUE #253: Menu item is not highlighted when using @RouteAlias
**Describe the bug**
If using a `@RouteAlias` the menu item related to the view does not get highlighted.

From my **very short** analysis the root cause might be inside `com.github.appreciated.app.layout.router.navigation.UpNavigationHelper#shouldHighlight` at
`HashMap<Class<? extends Component>, String> routes = getUpNavigationHelper().registeredRoutes;`.

It seems that the routes do not contain the aliases. Maybe you could use `RouteConfiguration.forRegistry(event.getSource().getRegistry()).getAvailableRoutes()` instead? Then you could pass the returned `RouteData` to `RouteSimilarity`. Nevertheless `RouteSimilarity` would need to handle the aliases returned by `RouteData.getRouteAliases()`.

**To Reproduce**
1. Add a view using an `@RouteAlias`
2. Navigate to the view using the alias in the url
3. Menu item is not highlighted.

**Expected behavior**
The menu item should be highlighted the same way it is using the normal route url.

**Additional Information (please complete the following information):**
 - OS: Windows
 - Browser: Chrome
 - Version: Vaadin 13.0.3, Addon: 2.0.1.beta1

### PR DESCRIPTION
**Pull request by Juchar**
Should fix #253 for V-10 branch.

### CODE REVIEW

**Comment by appreciated** [comment]
There seems to be some issue related to UpNavigation Highlighting. 
When starting the [demo](https://github.com/appreciated/vaadin-app-layout/blob/master/app-layout-addon/src/test/java/com/github/appreciated/app/layout/MainLayout.java).
And navigating to `http://127.0.0.1:8080/view2/subcontent` the closest menu entry `http://127.0.0.1:8080/view2` is no longer highlighted. 

Can you please have a look into this?

**Comment by Juchar** [comment]
I think I misunderstood the concept of the closest menu entry and that's why it is not working. I will have a second look on monday as I will not have the time during the weekend.

Nevertheless I am questioning the following:
Does it really make sense to highlight a menu entry if the exact path does not match?

**Comment by appreciated** [comment]
Can you please check if this works with route aliases? Maybe providing an ui test with route aliases is a good idea, since this will ensure that route aliases will be supported in future 😉.

**Comment by Juchar** [comment]
@appreciated I think you forgot to add the up navigation to the `TopNavigationLink`.
Additionally I added some ui tests for the route alias.

**Comment by Juchar** [comment]
@appreciated Do we need to update the V13 branch with the fix or did you cherry pick it?

**Comment by appreciated** [comment]
I already fixed this manually

**Pull request merged**
