### PR TITLE
Reimplementing Menus

### PR DESCRIPTION
**Pull request by appreciated**
* Closes issues
  * #175
  * #242
  * #236 
  * #230
  * #214 
* Also includes some styling fixes related to the Notifications
* Also adds some preparatory work for #222
* removes the paper-card dependency and replaced it with my personal [card](https://github.com/appreciated/card) dependency

### CODE REVIEW

**Comment by appreciated** [comment]
Please wait for the merge. I just found a styling issue related to Up-navigation and Small Menus

**Comment by appreciated** [comment]
@Springrbua I would say we should merge this now, even if back-navigation Highlighting is currently not supported. 
Supporting back navigation highlighting is not that easy, since it requires all menu items that have been added to the menu to be evaluated. 
I will make an enhancement issue for this feature for another day

**Comment by Springrbua** [comment]
@appreciated Unfortunately, there are too many changes for me to review it.
But I will test the new version once it is released and give you feedback based on this.

**Comment by appreciated** [comment]
> Unfortunately, there are too many changes for me to review it.

Thats understandable, 

> But I will test the new version once it is released and give you feedback based on this.

Thank you very much

**Pull request merged**
