### PR TITLE
Serialization

### PR DESCRIPTION
**Pull request by smogstate**
Those components must be serializable. This is not critical until you dont do session replication.

### CODE REVIEW

**Comment by appreciated** [comment]
Thank you very much for the PR and the time you put into this! Unfortunatly since I'm currently changing my residence I don't have much time for looking into this but as soon as I have more time I promise I will do so.

**Comment by deyaeddin** [comment]
Hi Denis,
I'm interested in your approach, but I tried to test your pull code on Spring Boot project. I keep getting the following error:

NOTE: I'm using this code for HttpSession
`		WrappedSession session = vaadinRequest.getWrappedSession();
		HttpSession httpSession = ((WrappedHttpSession) session).getHttpSession();
`

can you do more tests?

```
Caused by: com.vaadin.server.ServiceException: java.lang.NoSuchMethodError: com.github.appreciated.app.layout.builder.steps.CDIBuilderNavigatorPreamble.withViewProvider(Ljava/util/function/Supplier;)Lcom/github/appreciated/app/layout/builder/steps/CDIBuilderViewNameProviderPreamble;
	at com.vaadin.server.VaadinService.handleExceptionDuringRequest(VaadinService.java:1653)
	at com.vaadin.server.VaadinService.handleRequest(VaadinService.java:1613)
	at com.vaadin.server.VaadinServlet.service(VaadinServlet.java:445)
	... 118 common frames omitted
```

**Comment by appreciated** [comment]
@smogstate Could you please investigate the issues @deyaeddin mentioned?

**Comment by smogstate** [comment]
ye ofc, i am kinda ill now, will do this week.

**Comment by smogstate** [comment]
Hi Deya.

can you please push somewhere you project? I am not that familiar with spring boot. Generally this pull works in jee app server, i am replicating user session, and it works. Its seems you have some package which is compiled against original jar and not against my pull.

**Comment by smogstate** [comment]
@appreciated well that is tricky part, lambda is not serializable, you **need** to cast it to some serializable functional interface then.

**Comment by deyaeddin** [comment]
@smogstate can you send me a line to deya@gmx.com so I can give you an access to the repository! It's a private Project.

**Comment by smogstate** [comment]
@deyaeddin yes its my email :)

**Comment by appreciated** [comment]
@smogstate any updates on this PR?

**Comment by smogstate** [comment]
@appreciated you manage to solve problems with spring? this branch is working in already 2 jee projects fine :)

**Comment by deyaeddin** [comment]
Hi Denis,
I've sent you a Spring Boot project by email based on your fork, let's take to Slack.

**Comment by appreciated** [comment]
Closing due to inactivity

**Pull request closed without merging**
